### ISSUE TITLE
Adaptation of Credential Documentation Repository

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/tractusx-profiles#25]
## Description
This change ticket aims to adapt the credential documentation repository by adding the new credentials 

- CircularEconomyCredential
- DemandCapacityCredential
- PurisCredential
- BusinessPartnerCredential

Furthermore, it includes the removal of the 
- Sustainability
- Resilience

<br>

`Relevant Release: 24.05`
Standards are up to date; @jjeroch has initiated the change 3 weeks ago.

<br>
<br>

## Changes to be Made
1. Add the `CircularEconomyCredential` to the documentation repository.
2. Add the `DemandCapacityCredential` to the documentation repository.
3. Add the `PurisCredential` to the documentation repository.
4. Add the `BusinessPartnerCredential` to the documentation repository.
6. Remove the `sustainability` credential from the documentation repository.
7. Remove the `resilience` credential from the documentation repository.

## Reason for Change
The addition of the new credentials will enhance the documentation repository by providing comprehensive coverage of the latest credentials. Additionally, the removal of the `sustainability` and `resilience` credentials is necessary due to their outdated relevance.

## Impact Analysis
- **Positive Impact:** The addition of new credentials will improve the repository's credibility and ensure up-to-date documentation.

## Implementation Plan
1. Review the existing documentation repository and identify the sections where the new credentials need to be added.
2. Update the repository by including the new credentials.
3. Remove all references to the old credentials from the documentation.
4. Conduct a thorough review of the updated repository to ensure accuracy and completeness.

**Comment by arnoweiss** [comment]
This should be outdated, right?

**Comment by arnoweiss** [comment]
The only reason to add these credentials now is for backward compatibility as they will be removed in August anyway.

**Comment by arnoweiss** [comment]
Added the to-be-removed sections to #37. Thus, this is closable from #39
