### ISSUE TITLE
Make credential-context resolvable

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/tractusx-profiles#26]
### Description
**As** Operator or Enablement Service Provider for a CX-0018 compliant service,
**I want** to read the expanded JSON-LD of VCs,
**so that** I can reliably process and understand their content.

### Acceptance Criteria

- [x] `https://w3id.org/catenax/credentials/v1.0.0` is resolvable to a JSON-LD context.
- [ ] The versioning between the context and the namespace is aligned.

### Additional Information
Currently, the samples' `@context` in the [credentials-folder](https://github.com/eclipse-tractusx/tractusx-profiles/tree/main/cx/credentials) rely on the `https://w3id.org/catenax/credentials/v1.0.0` context. It currently resolves to the default path specified in the [redirects](https://github.com/perma-id/w3id.org/blob/master/catenax/.htaccess). The credential-context included in this repository is already in v1.1 so I'm unsure whether it's an appropriate target. Its content would be affected if issue #25 is accepted with further implications for versioning.

I'd be willing to contribute if there's an aligned concept.

**Comment by arnoweiss** [comment]
@jimmarino - is this on your roadmap? If no, I could pick this up. EDC doesn't need it but I think there's value in it.

Note: The original issue mentions `https://w3id.org/catenax/...` while there's consensus now that the contexts should reside in the `https://w3id.org/tractusx/...` namespace.

**Comment by jimmarino** [comment]
@arnoweiss If you could pick this up it would be much appreciated.

**Comment by arnoweiss** [comment]
Created a PR in the `https://w3id.org/catenax/` namespace for the credentials [1] and one to register `https://w3id.org/tractusx` and populate it with a redirect to the policy-jsonld-context [2]. 

[1] https://github.com/perma-id/w3id.org/pull/4059
[2] https://github.com/perma-id/w3id.org/pull/4060

**Comment by wolf4ood** [comment]
Hey @arnoweiss  thanks!

Just a small comment for the links. I would use the published on in GH pages, 
since they will be updated automatically in when changed and also GH pages preserve the content type, some libraries complain about the `raw.*` of GH since the content type i think it's `plain/text`

You can find the published one here:

Policy Context
https://eclipse-tractusx.github.io/tractusx-profiles/cx/context/policy.context.json

Credentials Context
https://eclipse-tractusx.github.io/tractusx-profiles/cx/context/credentials.context.json

**Comment by arnoweiss** [comment]
Thanks, I wasn't aware that exists. 

As the documents you linked mirror `main`, it may become an issue that they are mutable. Fetching the context from remote may yield varying results. I think it's good enough for now but this may become an issue further down the road. I'll adjust the linked PRs.

**Comment by arnoweiss** [comment]
The respective PRs are merged and resolve correctly AFAICT. Please check and close if confirmed.

**Comment by wolf4ood** [comment]
Thanks @arnoweiss  

LGTM!
