### ISSUE TITLE
Catena-X concepts are namespaced with https://w3id.org/tractusx/policy/

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/tractusx-profiles#28]
### Current Behavior
Currently, the Policy Context expands multiple resources with `https://w3id.org/tractusx/policy/`.

https://github.com/eclipse-tractusx/tractusx-profiles/blob/c1be580c9073230de1f740c788d846f2636373b8/cx/credentials/schema/context/policy.context.json#L11

### Expected Behavior
As terms like "Membership", "FrameworkAgreement" etc are semantically described in https://github.com/catenax-eV/cx-odrl-profile/, implementations using them should refer to the same URI - if they don't, the concepts can't be assumed to be equivalent.

**Comment by MaximilianHauer** [comment]
@arnoweiss  / @jimmarino  could it be that the url is not existing anymore ? it gets forwarded to the tractus-x page 

if this was merged to cx-odrl-profile we miss the namespace for businesspartnergroup

**Comment by arnoweiss** [comment]
The namespace URI never resolved as there was no point in it. Resolution is only a requirement for remote contexts as that can actually cause issues at runtime. Providing human-readable text or turtle (ttl) is a best practice but was never required. Please open a new issue if that's changing.
