### ISSUE TITLE
[Trufflehog Update] Add Trufflehog secret scanning workflow

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/tractusx-profiles#40]
## Description

The GitGuardian secret scanning tool licence is now expired, therefore in order to maintain the Security of the Tractus-X Repositories there will be inforced the [TRG-8.03](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-03) for all Tractus-X repos.

## Incident Ticket

https://github.com/eclipse-tractusx/sig-security/issues/86

Your repository was found in one of our security scans, and it was listed along with other repositories for not contain any of this files:

```md
".github/workflows/trufflehog.yaml"
".github/workflows/trufflehog.yml"
".github/workflows/secrets-scan.yml"
```

Please read the [TRG-8.03](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-03) and create the workflow file as soon as posible!

## What needs to be done?

- [ ] Add the Trufflehog workflow like described in [TRG-8.03](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-03) to the `/.github/workflows` folder
- [ ] Remove all references to GitGuardian from documentation
- [ ] Create a PR and Merge it to `main`
- [ ] As committer: revise if any secrets were found in the scan (in the security tab)
- [ ] Close this ticket

Thank you very much for doing the update! 🚀

If there is any question, please let us know,  
Your Tractus-X Project Leads 💯

**Comment by lgblaumeiser** [comment]
Hi @matbmoser , I have discussed with the EDC committers. We came to the conclusion, that this repository should be omitted from a TruffleHog scan as well, as it is only used to maintain some profile files which are purely declarative.

**Comment by matbmoser** [comment]
Fine for me, please tell me which ones also do not need the trufflehog scan, I wish we could talk about this in the Committer meeting too :)

**Comment by lgblaumeiser** [comment]
From the list I saw 4 repositories, which are in EDC team control. From these, two have been updates and this and the template repo we decided, that the scan does not make sense. So we are done, based on the list in the parent item. Unfortunately, I cannot discuss this in the committer meeting 😦
